# Generated by Django 3.2.9 on 2022-02-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dog_guide_course',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kurs Przewodników'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kpp_course',
            field=models.BooleanField(blank=True, null=True, verbose_name='KPP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_exam',
            field=models.BooleanField(blank=True, null=True, verbose_name='Badania Lekarskie'),
        ),
        migrations.AlterField(
            model_name='member',
            name='osp_course',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kurs OSP'),
        ),
    ]
