# Generated by Django 3.2.9 on 2022-02-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220210_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owned_dog',
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.member', verbose_name='Właściciel'),
        ),
    ]
