# Generated by Django 3.2.9 on 2022-02-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_dog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name_plural': 'Psy'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Sprzęt'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': 'Kategorie sprzętu'},
        ),
        migrations.AlterModelOptions(
            name='fleet',
            options={'verbose_name_plural': 'Flota'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Lista członków'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='field_exam_0',
            field=models.BooleanField(blank=True, choices=[('TAK', 'Tak'), ('NIE', 'Nie')], default='NO', null=True, verbose_name='Egzamin teren 0'),
        ),
    ]
