# Generated by Django 3.2.9 on 2022-02-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_alter_dog_field_exam_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='field_exam_0',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default=0, max_length=3, null=True, verbose_name='Egzamin teren 0'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='field_exam_1',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default=0, max_length=3, null=True, verbose_name='Egzamin teren 1'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_0',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default=0, max_length=3, null=True, verbose_name='Egzamin gruzy 0'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_1',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default=0, max_length=3, null=True, verbose_name='Egzamin gruzy 1'),
        ),
    ]
