# Generated by Django 3.2.9 on 2022-02-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_dog_field_exam_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='field_exam_1',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin teren 1'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_0',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin gruzy 0'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_1',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin gruzy 1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dog_guide_course',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Kurs Przewodników'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kpp_course',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='KPP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_exam',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Badania Lekarskie'),
        ),
        migrations.AlterField(
            model_name='member',
            name='osp_course',
            field=models.CharField(blank=True, choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Kurs OSP'),
        ),
    ]
