# Generated by Django 3.2.9 on 2022-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_member_kpp_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='kpp_course',
            field=models.CharField(choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='KPP'),
        ),
    ]
