# Generated by Django 3.2.9 on 2022-02-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20220219_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='field_exam_0',
            field=models.CharField(choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin teren 0'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='field_exam_1',
            field=models.CharField(choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin teren 1'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_0',
            field=models.CharField(choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin gruzy 0'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ruins_exam_1',
            field=models.CharField(choices=[('NIE', 'Nie'), ('TAK', 'Tak')], default='NIE', max_length=3, null=True, verbose_name='Egzamin gruzy 1'),
        ),
    ]
