# Generated by Django 4.0.2 on 2022-02-20 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_alter_member_member_id_delete_myuuidmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=5, null=True, unique=True, verbose_name='ID'),
        ),
    ]
