# Generated by Django 4.0.2 on 2022-02-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_member_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_id',
        ),
    ]
