# Generated by Django 4.0.2 on 2022-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_remove_member_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
