# Generated by Django 4.0.2 on 2022-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0026_dog_dog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_slug',
            field=models.SlugField(unique=True),
        ),
    ]
