# Generated by Django 4.0.2 on 2022-02-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_alter_dog_dog_slug_alter_member_member_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='register.member', verbose_name='Właściciel'),
        ),
    ]
