# Generated by Django 4.0.2 on 2022-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0030_rename_dog_slug_dog_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontakt'),
        ),
    ]
