# Generated by Django 4.0.2 on 2022-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_alter_member_member_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='kpp_validity',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Termin ważności KPP'),
        ),
        migrations.AlterField(
            model_name='member',
            name='medical_exam_validity',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Termin ważności badań'),
        ),
    ]
