# Generated by Django 4.0.2 on 2022-02-22 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_alter_member_kpp_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
