# Generated by Django 4.0.2 on 2022-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_alter_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_ref_id',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='RefID'),
        ),
    ]
